sources:
  - build/LXGWWenKaiMonoTC-Bold.designspace
  - build/LXGWWenKaiMonoTC-Light.designspace
  - build/LXGWWenKaiMonoTC-Regular.designspace
  - build/LXGWWenKaiTC-Bold.designspace
  - build/LXGWWenKaiTC-Light.designspace
  - build/LXGWWenKaiTC-Regular.designspace
removeOutlineOverlaps: False
buildOTF: False
buildTTF: True
buildWebfont: False
autohintTTF: False
reverseOutlineDirection: False
