sources:
  - build/LXGWWenKaiMonoTC-Light.designspace
  - build/LXGWWenKaiMonoTC-Medium.designspace
  - build/LXGWWenKaiMonoTC-Regular.designspace
  - build/LXGWWenKaiTC-Light.designspace
  - build/LXGWWenKaiTC-Medium.designspace
  - build/LXGWWenKaiTC-Regular.designspace
reverseOutlineDirection: False
removeOutlineOverlaps: False
buildOTF: False
buildTTF: True
buildWebfont: False
autohintTTF: False

outputDir: ../fonts
ttDir: $outputDir/TTF
otDir: $outputDir/OTF
