name: Package fonts and upload to release

on: 
  release:
    # do not run when created/draft, only when finalised
    types: [published]

jobs:
  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      FULL_ZIP_NAME: lxgw-wenkai-tc-${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
      
      # zip license
      - run: cp OFL.txt fonts/TTF/OFL.txt
      
      - name: Zip files
        run: |
          cd fonts
          mv TTF ${{ env.FULL_ZIP_NAME }}
          zip -r ${{ env.FULL_ZIP_NAME }}.zip ${{ env.FULL_ZIP_NAME }}
          tar -czvf ${{ env.FULL_ZIP_NAME }}.tar.gz ${{ env.FULL_ZIP_NAME }}
          mv ${{ env.FULL_ZIP_NAME }} TTF
          cp ${{ env.FULL_ZIP_NAME }}.zip TTF/${{ env.FULL_ZIP_NAME }}.zip
          cp ${{ env.FULL_ZIP_NAME }}.tar.gz TTF/${{ env.FULL_ZIP_NAME }}.tar.gz
        
      # remove license
      - run: rm fonts/TTF/OFL.txt
      
      # upload files to releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: fonts/TTF/*
          tag: ${{ github.ref }}
          overwrite: true
